about:
    home: http://hgomersall.github.com/pyFFTW
    license: GPL
    summary: pyfftw
build:
    number: '1'
package:
    name: pyfftw
    version: 0.9.2
requirements:
    build:
    - fftw
    - cython
    - pkg-config [osx]
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - cython
    - fftw
    - numpy x.x
    - python x.x
source:
    fn: pyFFTW-0.9.2.tar.gz
    url:
    - https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.9.2.tar.gz
test:
    imports:
    - pyfftw
