{% set name = 'mosviz' %}
{% set version = '0.3.0' %}
{% set tag = version %}
{% set number = '1' %}

about:
  home: https://github.com/spacetelescope/mosviz
  license: BSD
  summary: |
        Quick-look analysis and visualization tool for multi-object spectroscopy

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: {{ number }}

source:
  git_tag: {{ tag }}
  git_url: https://github.com/spacetelescope/mosviz.git

requirements:
  build:
    - astropy
    - glue-core >=0.11.0
    - matplotlib >=1.5.3
    - specutils >=0.5.1
    - numpy {{ numpy }}
    - python {{ python }}
    - specviz >=0.6.2
    - setuptools_scm

  run:
    - astropy
    - glue-core >=0.11.0
    - matplotlib >=1.5.3
    - specutils >=0.5.1
    - specviz >=0.6.2
    - numpy
    - python

test:
  requires:
    - astropy
    - specutils >=0.5.1
    - specviz >=0.6.2
  imports:
    - mosviz

