{% set name = 'mosviz' %}
{% set version = '0.1.1' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set tag = 'v' + version %}
{% set number = '1' %}

about:
  home: https://github.com/spacetelescope/mosviz
  license: BSD
  summary: |
        Quick-look analysis and visualization tool for multi-object spectroscopy

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: {{ number }}

source:
  git_tag: {{ tag }}
  git_url: https://github.com/spacetelescope/mosviz.git

requirements:
  build:
    - astropy
    - glue-core >=0.11.0
    - matplotlib >=1.5.3
    - specutils <=0.2.2
    - numpy {{ numpy }}
    - python {{ python }}

  run:
    - astropy
    - glue-core >=0.11.0
    - matplotlib >=1.5.3
    - specutils <=0.2.2
    - numpy
    - python

test:
  requires:
    - astropy
    - specutils <=0.2.2
  imports:
    - mosviz

