{% set name = 'nictools' %}
{% set version = '1.1.3' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '2' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    summary: |
        Python tools for NICMOS data

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - astropy >=1.1
    - numpy {{ numpy }}
    - scipy
    - stsci.tools
    - setuptools
    - python {{ python }}
    run:
    - astropy >=1.1
    - numpy
    - scipy
    - stsci.tools
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - nictools
