{% set name = 'dust_extinction' %}
{% set version = '0.7' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/karllark/{{ name }}
    license: BSD
    summary: |
        Models of interstellar dust extinction curves

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=2
    - pytest
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=2
    - matplotlib
    - scipy
    - numpy
    - python

source:
    git_tag: {{ tag  }}
    git_url: https://github.com/karllark/{{ name }}.git

test:
    imports:
    - dust_extinction
