{% set name = 'drizzlepac' %}
{% set version = '3.3.0' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: AstroDrizzle for HST images

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - acstools
    - astropy>=4.0.0
    - astroquery>=0.4
    - bokeh
    - fitsblender
    - graphviz
    - jeepney
    - lxml
    - nictools
    - nose
    - scikit-learn>=0.20
    - scipy
    - secretstorage [linux]
    - spherical-geometry
    - stsci.image>=2.3.4
    - stsci.imagestats
    - stsci.skypac>=1.0.7
    - stsci.stimage
    - stsci.tools>=4.0
    - stwcs>=1.5.3
    - stregion
    - setuptools
    - pandas
    - photutils>=1.0.0
    - pysynphot
    - pypdf2
    - pytables
    - tweakwcs>=0.7.2
    - numpy=>1.19
    - python {{ python }}
    run:
    - acstools
    - astropy
    - astroquery
    - bokeh
    - fitsblender
    - nictools
    - nose
    - jeepney
    - lxml
    - scikit-learn
    - scipy
    - secretstorage [linux]
    - spherical-geometry
    - stsci.image
    - stsci.imagestats
    - stsci.skypac
    - stsci.stimage
    - stsci.tools
    - stwcs
    - stregion
    - setuptools
    - pandas
    - photutils
    - pysynphot
    - pypdf2
    - pytables
    - tweakwcs
    - numpy
    - python
 

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
      - drizzlepac
