{% set name = 'reproject' %}
{% set version = '0.4' %}
{% set tag = 'v' + version %}
{% set number = '2' %}

about:
  home: http://reproject.readthedocs.io/
  license: BSD
  summary: |
    Reproject astronomical images

build:
  number: {{ number }}

package:
  name: {{ name }}
  version: {{ version }}

requirements:
  build:
    - astropy >=2.0
    - astropy-healpix >=0.2
    - cython
    - scipy >=0.9
    - setuptools <38.5.1 [(py2k or py35 or py36) and osx]
    - setuptools [(py37 and osx) or linux]
    - numpy {{ numpy }}
    - python {{ python }}

  run:
    - astropy >=2.0
    - astropy-healpix >=0.2
    - scipy >=0.9
    - numpy
    - python

source:
  git_tag: {{ tag }}
  git_url: https://github.com/astrofrog/{{ name }}.git

test:
  imports:
    - reproject
