{% set name = 'reproject' %}
{% set version = '0.4' %}
{% set tag = 'v' + version %}
{% set number = '1' %}

about:
  home: http://reproject.readthedocs.io/
  license: BSD
  summary: |
    Reproject astronomical images

build:
  number: {{ number }}

package:
  name: {{ name }}
  version: {{ version }}

requirements:
  build:
    - astropy >=1.0
    - astropy-healpix
    - cython
    - scipy >=0.9
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}

  run:
    - astropy >=1.0
    - astropy-healpix
    - scipy >=0.9
    - numpy
    - python

source:
  git_tag: {{ tag }}
  git_url: https://github.com/astrofrog/{{ name }}.git

test:
  imports:
    - reproject
