{% set name = 'reftools' %}
{% set version = '1.7.2' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: For HST reference files
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.1
    - numpy x.x
    - python x.x
    - setuptools
    run:
    - astropy >=1.1
    - numpy x.x
    - python x.x
source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
test:
    commands:
    - tdspysyn --help
    imports:
    - reftools
