{% set name = 'reftools' %}
{% set version = '1.7.4' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: For HST reference files

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - numpy {{ numpy }}
    - python {{ python }}
    - setuptools
    run:
    - astropy >=1.1
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - tdspysyn --help
    imports:
    - reftools
