{% set name = 'stsci-data-analysis' %}
{% set version = '3.0.0' %}
{% set number = '0' %}

about:
    home: http://ssb.stsci.edu
    license: BSD
    summary: stsci-data-analysis meta-package

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - numpy {{ numpy }}
      - python {{ python }}

    run:
      - asdf >=1.3.1
      - astroimtools >=0.1.1
      - cubeviz <=0.2.1
      - gwcs >=0.9.1
      #- mosviz >=0.1.1  # disabled
      - photutils >=0.4
      - imexam >=0.8.0
      #- specutils >=0.2.2  # disabled
      - specviz <0.6.0
      - spherical-geometry >=1.0.12
      - stginga >=0.2.1
      - python
