{% set name = 'stsci-data-analysis' %}
{% set version = '2.2.0' %}
{% set number = '0' %}

about:
    home: http://ssb.stsci.edu
    license: BSD
    summary: stsci-data-analysis meta-package

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - numpy {{ numpy }}
      - python {{ python }}

    run:
      - asdf >=1.3.1
      - astropy >=2.0.0
      - astroimtools >=0.1.1
      - cubeviz >=0.0.2
      - glueviz >=0.12.0
      - glue-vispy-viewers >=0.9
      - gwcs >=0.8.0
      - mosviz >=0.1.1
      - photutils >=0.4
      - imexam >=0.8.0
      - specutils >=0.2.2
      - specviz >=0.4.4
      - spherical-geometry >=1.0.12
      - stginga >=0.2.1
      - numpy
      - python
