about:
    home: http://stsci.edu
    license: BSD
    summary: stsci-data-analysis meta-package
build:
    number: '0'
package:
    name: stsci-data-analysis
    version: 1.1.1
requirements:
    build:
    - astropy >=1.1
    - astroimtools >=0.1
    - stginga >=0.1
    - specviz
    - mosviz
    - photutils >=0.2.2
    - glueviz >=0.9.0
    - imexam >=0.6.2
    - asdf >=1.0.2
    - numpy x.x
    - python x.x
    run:
    - astropy >=1.1
    - astroimtools >=0.1
    - stginga >=0.1
    - specviz
    - mosviz
    - photutils >=0.2.2
    - glueviz >=0.9.0
    - imexam >=0.6.2
    - asdf >=1.0.2
    - numpy x.x
    - python x.x
