{% set name = 'stsci-data-analysis' %}
{% set version = '3.0.0' %}
{% set number = '0' %}

about:
    home: http://ssb.stsci.edu
    license: BSD
    summary: stsci-data-analysis meta-package

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - numpy {{ numpy }}
      - python {{ python }}

    run:
      - asdf >=1.3.1
      - astroimtools >=0.1.1
      #- cubeviz <=0.2.1  # Excluded due to spec(utils|viz). and mosviz conflicts
      - da5-notebooks >=1.0.0
      - gwcs >=0.9.1
      - mosviz >=0.1.1
      - photutils >=0.6
      - imexam >=0.8.1
      - specutils >=0.2.2  # Constraint permits manual cubeviz install
      - specviz >=0.5.0    # Constraint permits manual cubeviz install
      - spherical-geometry >=1.2.6
      - stginga >=0.2.1
      - tweakwcs >=0.1.1
      - webbpsf >=0.8.0
      - python
