{% set name = 'poppy' %}
{% set version = '1.0.2' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Physical optics propagation (wavefront diffraction) for optical
        simulations, particularly of telescopes

build:
    number: {{ number }}
    skip: true # [py27]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=4.0.0
    - numpy {{ numpy }}
    - scipy >=1.5.0
    - matplotlib >=3.2.0
    - setuptools
    - setuptools_scm
    - fonttools >=4.22.0
    - python {{ python }}

    run:
    - astropy >=4.0.0
    - numpy >=1.18.0
    - scipy >=1.5.0
    - matplotlib >=3.2.0
    - setuptools
    - setuptools_scm
    - fonttools >=4.22.0
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
