about:
    home: https://github.com/mperrin/poppy
    license: BSD
    summary: poppy
build:
    number: '0'
package:
    name: poppy
    version: 0.5.1
requirements:
    build:
    - astropy >=1.1
    - numpy x.x
    - scipy
    - matplotlib
    - six [py27]
    - enum34 [py27]
    - setuptools
    - python x.x
    run:
    - astropy >=1.1
    - numpy x.x
    - scipy
    - matplotlib
    - six [py27]
    - enum34 [py27]
    - setuptools
    - python x.x
source:
    git_tag: v0.5.1
    git_url: https://github.com/mperrin/poppy
