{% set name = 'poppy' %}
{% set version = '0.8.0' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Physical optics propagation (wavefront diffraction) for optical
        simulations, particularly of telescopes

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.3
    - numpy {{ numpy }}
    - scipy >=0.14.0
    - matplotlib >=1.3.0
    - setuptools
    - python >= 3.5
    run:
    - astropy >=1.1
    - numpy
    - scipy >=0.14.0
    - matplotlib >=1.3.0
    - setuptools
    - python >= 3.5

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
