{% set name = 'cfitsio' %}
{% set version = '3.390' %}
{% set badversion = '3390' %}
{% set number = '0' %}
about:
    home: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
    license: BSD-like
    summary: |
        CFITSIO is a library of C and Fortran subroutines for reading and
        writing data files in FITS (Flexible Image Transport System) data format

build:
    number: {{number}}

package:
    name: {{name}}
    version: {{version}}

source:
    fn: {{name}}{{badversion}}.tar.gz
    url: ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/{{name}}{{badversion}}.tar.gz
