{% set name = 'stsci' %}
{% set version = '3.1.0' %}
{% set number = '0' %}

about:
    home: http://ssb.stsci.edu
    license: BSD
    summary: stsci meta-package

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - numpy {{ numpy }}
      - python {{ python }}

    run:
      - stsci-hst >=3.1.0
      - stsci-data-analysis >=2.1.1
      - astropy >=2.0.0
      - cfitsio >=3.370
      - d2to1 >=0.2.12
      - ds9 >=7.1
      - fftw >=3.3.4
      - htc_utils >=0.1
      - pyds9 >=1.8.1
      - pyfftw >=0.9.2
      - numpy
      - python
