{% set name = 'dbus-glib' %}
{% set version = '0.108' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '0' %}
{% set archive = name + '-' + version + '.tar.gz' %}

package:
   name: {{ name }}
   version: {{ version }}

build:
   skip: true [not linux]
   number: {{ number }}

requirements:
  build:
    - pkg-config
    - dbus
    - expat
    - glib
    # - selinux (fat chance; this might cause issues)

  run:
    - dbus
    - expat
    - glib
    # - selinux (fat chance; this might cause issues)

source:
  fn: {{ archive }}
  url: https://dbus.freedesktop.org/releases/{{ name }}/{{ archive }}
