{% set name = 'pysiaf' %}
{% set version = '0.8.0' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary:
        Handling of Science Instrument Aperture Files (SIAF) for space telescopes

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

package:
    name: {{ name }}
    version: {{ version }}

build:
    number: {{ number }}

requirements:
    build:
    - astropy >=1.2
    - numpy >=1.13
    - matplotlib >=3.0.0
    - lxml >=3.6.4
    - scipy >=0.17
    - openpyxl >=2.6.0
    - python {{ python }}
    - setuptools
    - numpydoc
    - requests >=2.21.0
    - PyQt >=5.0.0

    run:
    - astropy >=1.2
    - numpy >=1.9
    - matplotlib >=1.4.3
    - lxml >=3.6.4
    - scipy >=0.17
    - openpyxl >=2.6.0
    - python {{ python }}
    - requests >=2.21.0
    - PyQt >=5.0.0

test:
    imports:
      - pysiaf
