{% set name = 'pysiaf' %}
{% set version = '0.14.0' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary:
        Handling of Science Instrument Aperture Files (SIAF) for space telescopes

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

package:
    name: {{ name }}
    version: {{ version }}

build:
    number: {{ number }}


requirements:
    build:
    - astropy >=4.3.1
    - numpy >=1.21.2
    - matplotlib >=3.4.3
    - lxml >=4.6.4
    - scipy >=1.7.2
    - openpyxl >=3.0.9
    - python {{ python }}
    - setuptools
    - numpydoc
    - requests >=2.26.0
    - PyQt >=5.0.0
    - et_xmlfile

    run:
    - astropy >=4.3.1
    - numpy >=1.21.2
    - matplotlib >=3.4.3
    - lxml >=4.6.4
    - scipy >=1.7.2
    - openpyxl >=3.0.9
    - python {{ python }}
    - requests >=2.26.0
    - PyQt >=5.0.0

test:
    imports:
      - pysiaf
