{% set name = 'stsci.skypac' %}
{% set version = '1.0.1' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: stsci.skypac

build:
    number: {{ number }}
    preserve_egg_dir: 'yes'
    skip: true  # [py2k]
    
package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=3.1
    - stsci.imagestats
    - spherical-geometry >=1.2.2
    - stsci.tools
    - stwcs
    - sphinx
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=3.1
    - stsci.imagestats
    - spherical-geometry >=1.2.2
    - stsci.tools
    - stwcs
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stsci.skypac
