{% set name = 'fftw' %}
{% set version = '3.3.5' %}
{% set number = '0' %}

about:
    home: http://www.fftw.org
    license: GPL
    summary: |
        FFTW is a C subroutine library for computing the discrete
        Fourier transform (DFT) in one or more dimensions, of arbitrary input
        size, and of both real and complex data.

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - pkgconfig
    run:
    - pkgconfig

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: http://www.fftw.org/{{ name }}-{{ version }}.tar.gz