{% set name = 'ginga' %}
{% set version = 'v2.6.0' %}
{% set number = '0' %}
about:
    home: https://github.com/ejeschke/{{ name }}
    license: BSD
    summary: Astronomical data visualization
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.2
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy >=1.2
    - numpy x.x
    - python x.x
source:
    git_tag: {{ version }}
    git_url: https://github.com/ejeschke/{{ name }}.git
test:
    commands:
    - ginga --help
    imports:
    - ginga
