{% set name = 'ginga' %}
{% set version = '2.6.2.1' %}
{% set tag = 'ab017d8' %}
{% set number = '1' %}

about:
    home: https://github.com/ejeschke/{{ name }}
    license: BSD
    summary: Astronomical data visualization

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.2
    - qtpy
    - setuptools
    - numpy
    - python x.x
    run:
    - astropy >=1.2
    - qtpy
    - numpy
    - python x.x

source:
    git_tag: {{ tag }}
    git_url: https://github.com/ejeschke/{{ name }}.git

test:
    commands:
    - ginga --help
    imports:
    - ginga
