{% set name = 'ginga' %}
{% set version = '3.0.1' %}
{% set tag = 'v' ~ version %}
{% set number = '0' %}

about:
    home: https://github.com/ejeschke/{{ name }}
    license: BSD
    summary: Astronomical data visualization

build:
    number: {{ number }}
    skip: true  # [py2k]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=3
    - qtpy
    - pillow
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=3
    - qtpy
    - pillow
    - numpy
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/ejeschke/{{ name }}.git

test:
    commands:
    - ginga --help
    imports:
    - ginga
