{% set name = 'ginga' %}
{% set verison = 'TBD' %}
{% set number = '0' %}
about:
    home: https://github.com/ejeschke/{{ name }}
    license: BSD
    summary: FITS file viewer
build:
    number: '0'
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.2
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy >=1.2
    - numpy x.x
    - python x.x
source:
    git_rev: TBD
    git_url: https://github.com/ejeschke/{{ name }}.git
test:
    imports:
    - ginga
