{% set name = 'ginga' %}
{% set version = '2.5.20160627100500' %}
{% set rev = '25d6608b' %}
{% set number = '0' %}
about:
    home: https://github.com/ejeschke/{{ name }}
    license: BSD
    summary: FITS file viewer
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.2
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy >=1.2
    - numpy x.x
    - python x.x
source:
    git_rev: {{ rev }}
    git_url: https://github.com/ejeschke/{{ name }}.git
test:
    imports:
    - ginga
