{% set name = 'ginga' %}
{% set verison = '2.5.20160603104100' %}
{% set rev = '2732be35' %}
{% set number = '0' %}
about:
    home: https://github.com/ejeschke/{{ name }}
    license: BSD
    summary: FITS file viewer
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.2
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy >=1.2
    - numpy x.x
    - python x.x
source:
    git_rev: {{ rev }}
    git_url: https://github.com/ejeschke/{{ name }}.git
test:
    imports:
    - ginga
