{% set name = 'photutils' %}
{% set version = '1.1.0' %}
{% set tag = version %}
{% set number = '0' %}

about:
  home: https://github.com/astropy/{{ name }}
  license: BSD
  summary: An Astropy package for photometry

build:
  number: {{ number }}
  skip: True  # [py<37]

package:
  name: {{ name }}
  version: {{ version }}

requirements:
  build:
    - cython
    - extension-helpers
    - setuptools
    - setuptools_scm
    - numpy {{ numpy }}
    - python {{ python }}
    - astropy >=4.0
  run:
    - python
    - astropy >=4.0
    - pytest-astropy
    - gwcs >=0.12
    - matplotlib >=2.2
    - numpy >=1.17
    - scikit-image >=0.14.2
    - scikit-learn >=0.19
    - scipy >=0.19

source:
  git_tag: {{ tag }}
  git_url: https://github.com/astropy/{{ name }}.git

test:
  requires:
    - pytest-astropy
  imports:
    - photutils
