{% set name = 'lapack' %}
{% set version = '3.6.0' %}
{% set number = '0' %}

about:
    home: http://www.netlib.org
    license: BSD
    summary: |
        LAPACK is written in Fortran 90 and provides routines for solving
        systems of simultaneous linear equations, least-squares solutions
        of linear systems of equations, eigenvalue problems, and singular
        value problems

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - cmake

source:
    fn: {{ name }}-{{ version }}.tgz
    url: http://www.netlib.org/{{ name }}/{{ name }}-{{ version }}.tgz
