{% set name = 'stsci.imagemanip' %}
{% set version = '1.1.2' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '2' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: STScI general image manipulation tools

build:
    number: {{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - numpy {{ numpy }}
    - stsci.distutils
    - stsci.tools
    - setuptools
    - python {{ python }}
    run:
    - numpy
    - stsci.tools
    - python

source:
    git_url: https://github.com/spacetelescope/{{ name }}

test:
    imports:
    - stsci.imagemanip
