{% set name = 'stsci.imagemanip' %}
{% set version = '1.1.2' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: STScI general image manipulation tools

build:
    number: {{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - numpy
    - stsci.distutils
    - stsci.tools
    - setuptools
    - python x.x
    run:
    - numpy
    - stsci.tools
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}

test:
    imports:
    - stsci.imagemanip
