{% set name = 'ccfits' %}
{% set badname = 'CCfits' %}
{% set version = '2.5' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '1' %}

about:
    home:
    license: BSD-like
    summary: |
        CCfits is an object oriented interface to the cfitsio library.

build:
    number: {{number}}

package:
    name: {{name}}
    version: {{version}}

requirements:
    build:
    - cfitsio >=3.08

    run:
    - cfitsio >=3.08

source:
    fn: {{badname}}-{{version}}.tar.gz
    url: http://heasarc.gsfc.nasa.gov/docs/software/fitsio/ccfits/{{badname}}-{{version}}.tar.gz
