{% set name = 'pyobjc-framework-cocoa' %}
{% set version = '3.1.1' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '0' %}

about:
    home: http://pyobjc.sourceforge.net/
    license: MIT
    summary: Wrappers for the Cocoa frameworks on Mac OS X

build:
    skip: True [not osx]
    number: {{ number }}
    preserve_egg_dir: 'true'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - pyobjc-core =={{ version }}
    - setuptools
    - python {{ python }}
    run:
    - pyobjc-core
    - python

source:
    fn: pyobjc-{{ version }}.tar.gz
    url: https://bitbucket.org/ronaldoussoren/pyobjc/get/pyobjc-{{ version }}.tar.bz2

test:
    imports:
    - Cocoa
