{% name = 'sextractor-generic' %}
{% version = '2.19.5' %}
{% number = '0' %}

about:
    home: http://www.astromatic.net/download/sextractor
    license: GPL
    summary: Generic (unoptimized) Source Extractor

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - fftw
    - pkgconfig
    - atlas-generic [osx]
    run:
    - fftw
    - atlas-generic [osx]

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: http://www.astromatic.net/download/{{ name }}/{{ name }}-{{ version }}.tar.gz
