{% set name = 'gwcs' %}
{% set version = '0.10.0' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Generalized World Coordinate System

build:
    number: {{ number }}
    skip: True [py27]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - asdf
    - astropy >=3.1
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - asdf
    - astropy >=3.1
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - gwcs
