{% set name = 'specviz' %}
{% set version = '0.5.0' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: {{ number }}

source:
  git_tag: {{ tag }}
  git_url: https://github.com/spacetelescope/specviz.git

requirements:
  build:
    - astropy
    - cython
    - docopt
    - specutils <=0.2.2
    - py-expression-eval
    - pyyaml
    - pyqtgraph >=0.9.11
    - pyqt
    - qtpy
    - scipy
    - spectral-cube
    - yaml
    - setuptools
    - six
    - numpy {{ numpy }}
    - python {{ python }}

  run:
    - astropy
    - cython
    - docopt
    - specutils <=0.2.2
    - py-expression-eval
    - pyyaml
    - pyqtgraph >=0.9.11
    - pyqt
    - qtpy
    - scipy
    - spectral-cube
    - yaml
    - six
    - numpy
    - python

test:
  requires:
    - astropy
    - specutils <=0.2.2
  imports:
    - specviz

about:
  home: https://github.com/spacetelescope/specviz
  license: BSD
  summary: An interactive astronomical 1D spectra analysis tool
