{% set name = 'specviz' %}
{% set version = '0.6.1' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: {{ number }}

source:
  git_tag: {{ tag }}
  git_url: https://github.com/spacetelescope/specviz.git

requirements:
  build:
    - asdf>=2.3.0
    - asteval>=0.9.13
    - astropy>=3.0.5
    - click>=7.0
    - gwcs>=0.9.1
    - pyqt>=5.9
    - pyqtgraph>=0.10.0
    - pytest>=4.0.1
    - pyyaml>=3.13
    - qtawesome>=0.5.3
    - qtpy>=1.5.2
    - scipy>=1.1.0
    - specutils>=0.5.1
    - numpy {{ numpy }}
    - python {{ python }}

  run:
    - asdf>=2.3.0
    - asteval>=0.9.13
    - astropy>=3.0.5
    - click>=7.0
    - gwcs>=0.9.1
    - numpy>=1.15.4
    - pyqt>=5.9
    - pyqtgraph>=0.10.0
    - pytest>=4.0.1
    - pyyaml>=3.13
    - qtawesome>=0.5.3
    - qtpy>=1.5.2
    - scipy>=1.1.0
    - specutils>=0.5.1
    - python

test:
  requires:
    - astropy >=3.0.5
    - specutils >=0.5.1
  imports:
    - specviz

about:
  home: https://github.com/spacetelescope/specviz
  license: BSD
  summary: An interactive astronomical 1D spectra analysis tool
