{% set name = 'specviz' %}
{% set version = '0.2.3' %}
{% set tag = 'v0.2.3' %}
{% set number = '0' %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: {{ number }}

source:
  git_tag: {{ tag }}
  git_url: https://github.com/spacetelescope/specviz.git

requirements:
  build:
    - astropy
    - cython
    - specutils
    - pyyaml
    - pyqtgraph >=0.9.11
    - pyqt
    - qtpy
    - scipy
    - yaml
    - setuptools
    - six
    - numpy
    - python x.x

  run:
    - astropy
    - cython
    - specutils
    - pyyaml
    - pyqtgraph >=0.9.11
    - pyqt
    - qtpy
    - scipy
    - yaml
    - six
    - numpy
    - python x.x

test:
  requires:
    - astropy
    - specutils
  imports:
    - specviz

about:
  home: https://github.com/spacetelescope/specviz
  license: BSD
