{% set name = 'fitsblender' %}
{% set version = '0.3.6' %}
{% set number = '1' %}

about:
    home: http://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Aggregate values in FITS headers

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - stsci.tools
    - setuptools
    - setuptools_scm
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=1.1
    - stsci.tools
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - fitsblender
