{% set name = 'glueviz' %}
{% set version = '0.10.0' %}
{% set number = '0' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 1bdd8b6925fb028938ee3affd7b95059

build:
  number: {{ number }}
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - glue = glue.main:main
    - glue-config = glue.config_gen:main
    - glue-deps = glue._deps:main
  osx_is_app: True

requirements:

  build:
    - python
    - setuptools
    - pyqt

  run:

    # The following is needed to make sure that the package works as a GUI
    # application (glue needs to be run with python.app, not python)
    - python.app  # [osx]

    # Required dependencies
    - python
    - numpy >=1.9
    - pandas >=0.14
    - astropy >=1.3
    - matplotlib >=1.4
    - qtpy >=1.1.1
    - ipython >=4.0
    - ipykernel
    - qtconsole
    - dill >=0.2
    - glue-vispy-viewers >=0.6
    - xlrd >=1.0
    - h5py >=2.4
    - setuptools >=1.0
    - pyqt

    # Optional dependencies (defined in ``extras_require``)
    - scipy
    - scikit-image
    - plotly

    # Temporary: the scikit-image conda package is missing the dask dependency
    # so we add it here for now
    - dask

test:
  imports:
    - glue
    - glue.core
    - glue.app.qt
  commands:
    - glue --version
    - glue-deps list

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration
