about:
    home: http://www.iac.es/proyecto/PyNeb/
    license: Unknown
    summary: A modern python tool to compute emission line emissivities
build:
    number: '1'
package:
    name: pyneb
    version: 1.0.14
requirements:
    build:
    - astropy
    - matplotlib
    - scipy
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy
    - matplotlib
    - scipy
    - numpy x.x
    - python x.x
source:
    fn: pyneb-1.0.14.tar.gz
    url:
    - https://pypi.python.org/packages/source/P/pyneb
test:
    imports:
    - pyneb
