{% set name = 'cubeviz' %}
{% set version = GIT_DESCRIBE_TAG ~ ".dev" ~ GIT_DESCRIBE_NUMBER ~ "+" ~ GIT_DESCRIBE_HASH %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Data analysis package for cubes.

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - asdf
    - asteval
    - astropy >=3.0
    - glue-core
    - specviz
    - spectral-cube
    - pytest >=3.1*
    - numpy {{ numpy }}
    - setuptools
    - python {{ python }}

    run:
    - asdf
    - asteval
    - astropy >=3.0
    - numpy
    - glue-core
    - specviz
    - spectral-cube
    - pytest >=3.1*
    - python

source:
    # This commit points to the 0.2.0 release candidate of Cubeviz.
    # This corresponds to tag 0.2.0rc on branch v0.2.x
    git_rev: b62d544c00293ec5509627dd2c2cef7800e1a9c1
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - cubeviz
