{% set name = 'cubeviz' %}
{% set version = '0.3.0' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Data analysis package for cubes.

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - asdf
    - asteval
    - astropy
    - glue-core >=0.14
    - numpy {{ numpy }}
    - pytest
    - setuptools
    - setuptools_scm
    - python {{ python }}

    run:
    - asdf
    - asteval
    - astropy
    - glue-core >=0.14
    - numpy >=1.13
    - pytest
    - specviz >=0.7.0
    - spectral-cube <0.4.4
    - python
    - pyqt5 <5.12

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - cubeviz
