{% set name = 'cubeviz' %}
{% set version = '0.2.0' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Data analysis package for cubes.

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - asdf
    - asteval
    - astropy
    - glue-core =0.13
    - numpy {{ numpy }}
    - pytest
    - setuptools
    - python {{ python }}

    run:
    - asdf
    - asteval
    - astropy
    - glue-core =0.13
    - numpy
    - pytest
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - cubeviz
