{% set reponame = 'synphot_refactor' %}
{% set name = 'synphot' %}
{% set version = '1.1.0' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ reponame }}
    license: BSD
    summary: Synthetic photometry using Astropy

build:
    number: {{ number }}
    skip: true  # [py2k]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - setuptools_scm
    - astropy >=3.2
    - extension-helpers
    - scipy >=1.1
    - numpy {{ numpy }}
    - pytest
    - setuptools
    - python {{ python }}
    run:
    - astropy >=3.2
    - scipy >=1.1
    - numpy
    - pytest
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ reponame }}.git

test:
    imports:
    - synphot
