{% set reponame = 'synphot_refactor' %}
{% set name = 'synphot' %}
{% set version = '0.2.0' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ reponame }}
    license: BSD
    summary: Synthetic photometry using Astropy

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=2.0
    - scipy >=0.14
    - numpy {{ numpy }}
    - pytest
    - setuptools
    - python {{ python }}
    run:
    - astropy >=2.0
    - scipy >=0.14
    - numpy
    - pytest
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ reponame }}.git

test:
    imports:
    - synphot
