{% set name = 'hstaxe' %}
{% set version = '1.0.0' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Spectral extraction tools for Hubble Space Telescope Grisms
        Based on the original aXe package.

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - setuptools
    - setuptools_scm
    - autoconf
    - automake
    - libtool
    - pkg-config
    - make
    - numpy {{ numpy }}
    - cfitsio
    - gsl
    - wcstools
    - python {{ python }}
    run:
    - numpy
    - astropy
    - cfitsio
    - gsl
    - stwcs
    - stsci.imagestats
    - drizzlepac
    - drizzle
    - wcstools

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - hstaxe
