{% set name = 'stsci.convolve' %}
{% set version = '2.2.0' %}
{% set number = '0' %}
about:
    home: https://github.com/spacetelescope/{{name}}
    license: GPL
    summary: "Image array convolution functions"

build:
    number: {{number}}
    preserve_egg_dir: 'yes'

package:
    name: {{name}}
    version: {{version}}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - numpy x.x
    - python x.x
    run:
    - numpy x.x
    - python x.x

source:
    git_tag: {{version}}
    git_url: https://github.com/spacetelescope/{{name}}.git

test:
    imports:
    - stsci.convolve
