{% set name = 'webbpsf-data' %}
{% set version = '0.8.0' %}
{% set number = '1' %}

about:
    home: https://webbpsf.readthedocs.io
    license: BSD
    summary: webbpsf data files

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: http://www.stsci.edu/~mperrin/software/webbpsf/{{ name }}-{{ version }}.tar.gz
