{% set name = 'shunit2' %}
{% set version = '2.0.3' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '1' %}

about:
    home: http://sourceforge.net/projects/{{ version }}
    license: LGPL
    summary: |
        shUnit2 is a xUnit unit test framework for Bourne based shell
        scripts, and it is designed to work in a similar manner to JUnit,
        PyUnit, etc

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tgz
    url: https://downloads.sourceforge.net/{{ name }}/{{ name }}-{{ version }}.tgz

test:
    commands:
    - shunit2 --help
