{% set name = 'xpa' %}
{% set version = '2.1.18' %}
{% set tag = 'v'+version %}
{% set number = '0' %}

about:
    home: https://github.com/ericmandel/xpa
    license: MIT
    summary: Provides seamless communication between many kinds of Unix programs

build:
    number: {{number}}

package:
    name: {{name}}
    version: {{version}}

source:
    git_tag: {{tag}}
    git_url: https://github.com/ericmandel/{{name}}.git

test:
    commands:
    - test -x `which xpaget`
    - test -x `which xpaset`
    - test -x `which xpainfo`
    - test -x `which xpaaccess`
    - test -x `which xpans`
