{% set badname = "PyOpenGL" %}
{% set name = badname|lower %}
{% set version = "3.1.3b1" %}
{% set number = '0' %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "e687eea7e006d65f531933b49b3b3d2feaaf51279147a904247f9d189762a36f" %}

about:
  home: http://pyopengl.sourceforge.net
  license: BSD License
  summary: Standard OpenGL bindings for Python

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  fn: '{{ badname }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ badname[0] }}/{{ badname }}/{{ badname }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: {{ number }}

requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python

test:
  imports:
    - OpenGL
    - OpenGL.GL
