{% set name = 'pyregion' %}
{% set version = '2.0' %}
{% set number = '1' %}

about:
    home: https://github.com/astropy/{{ name }}
    license: BSD
    summary: Python parser for ds9 region files

build:
    number: {{ number }}
    skip: True

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy
    - cython
    - numpy {{ numpy }}
    - pyparsing
    - python {{ python }}
    - setuptools
    run:
    - astropy
    - cython
    - numpy
    - pyparsing
    - setuptools
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/astropy/{{ name }}.git

test:
    imports:
    - pyregion
