{% set name = 'relic' %}
{% set version = '1.1.2' %}
{% set number = '5' %}

about:
    home: http://github.com/jhunkeler/{{ name }}
    license: BSD
    summary: Release I Control, for git

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - setuptools
    - python {{ python }}
    run:
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - relic
    - relic.release
    - relic.git
