{% set name = 'ccdproc' %}
{% set version = '1.3.0.post1' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
  home: http://ccdproc.readthedocs.io/
  license: BSD
  summary: |
    This is a package for reducing optical/IR CCD data that relies on astropy

build:
  number: {{ number }}

package:
  name: {{ name }}
  version: {{ version }}

requirements:
  build:
    - astropy >=1.0
    - decorator
    - astroscrappy
    - reproject
    - scikit-image
    - scipy
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}

  run:
    - astropy >=1.0
    - astroscrappy
    - decorator
    - reproject
    - scikit-image
    - scipy
    - numpy
    - python

source:
  git_tag: {{ tag }}
  git_url: https://github.com/astropy/{{ name }}.git

test:
  imports:
    - ccdproc
    - ccdproc.extern
    - ccdproc.tests
    - ccdproc.utils
    - ccdproc.utils.tests
