{% set name = 'aprio' %}
{% set version = '1.0.1' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: http://bitbucket.org/jhunkeler/aprio
    license: GPL
    summary: aprio is an automatic renice daemon.
build:
    number: '0'
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - python x.x
    - setuptools
    - psutil
    - python-daemon
    - docutils
    run:
    - psutil
    - python-daemon
    - docutils
    - python x.x
source:
    git_tag: {{ tag }}
    git_url: https://bitbucket.org/jhunkeler/{{ name }}.git
