{% set name = 'stsci.stimage' %}
{% set version = '0.2.2' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: stsci.stimage

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - d2to1
      - numpy {{ numpy }}
      - stsci.distutils
      - setuptools
      - python {{ python }}
    run:
      - numpy
      - python

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
      - stsci.stimage
