{% set name = 'jplephem' %}
{% set version = '2.9' %}
{% set number = '0' %}
about:
    home: https://github.com/brandon-rhodes/python-{{ name }}
    license: MIT
    summary: "Python version of NASA DE4xx ephemerides, the basis for the Astronomical Alamanac"

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}

    run:
    - numpy
    - python

source:
    git_url: https://github.com/brandon-rhodes/python-{{ name }}.git
    patches:
    - 0001_use-setuptools.patch

test:
    imports:
    - jplephem
    - jplephem.spk
