{% set name = 'hstcal' %}
{% set version = '2.3.1' %}
{% set number = '3' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Calibration for HST/WFC3, HST/ACS, and HST/STIS

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - python {{ python }}
      - cfitsio >=3.440
      - pkg-config
      - gcc_linux-64 [linux]
      - gfortran_linux-64 [linux]
      # OS-provided compilers and macos SDK used.
      # The conda toolchains do not work on macos.

    run:
      - cfitsio
      - libgcc >=4.7

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
  commands:
    - calacs.e --gitinfo
    - otool -L $(which calacs.e) [osx]
    - ldd $(which calacs.e) [linux]
