{% set name = 'crds' %}
{% set version = '7.1.0' %}
{% set number = '1' %}

about:
    home: http://www.stsci.edu/hst/observatory/crds/
    license: AURA
    summary: |
        CRDS assigns calibration references to data using formal rules
        represented in simple text files

build:
    number: {{ number }}
    preserve_egg_dir: 'no'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - astropy >=1.1
    - numpy
    - setuptools
    - python x.x
    run:
    - astropy >=1.1
    - numpy
    - python x.x

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - crds
