{% set name = 'pysynphot' %}
{% set version = '0.9.8.4' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/pysynphot
    license: BSD
    summary: Synthetic Photometry Package
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.1
    - numpy x.x
    - python x.x
    - setuptools
    run:
    - astropy >=1.1
    - numpy x.x
    - python x.x
source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
test:
    imports:
    - pysynphot
