{% set name = 'pysynphot' %}
{% set version = '2.0.0' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Synthetic Photometry Package
build:
    number: {{ number }}
    skip: true  # [py2k]
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.1
    - beautifulsoup4
    - numpy {{ numpy }}
    - pytest
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - six
    run:
    - astropy >=1.1
    - beautifulsoup4
    - numpy
    - pytest
    - python
    - six
source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
test:
    imports:
    - pysynphot
