{% set name = 'stsci.tools' %}
{% set version = '4.0.0' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/stsci.tools
    license: BSD
    summary: |
        Collection of tools specific to STScI packages

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - setuptools
    - pytest-runner
    - numpy {{ numpy }}
    - python {{ python }}

    run:
    - astropy >=1.1
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}

test:
    imports:
    - stsci.tools
