{% set name = 'ds9' %}
{% set version = '7.4.1' %}
{% set number = '0' %}

package:
    name: {{name}}
    version: {{version}}

build:
    number: {{number}}

requirements:
    build:
    - gcc >=4.6 [osx]

source:
    fn: {{name}}.{{version}}.tar.gz
    url: http://ds9.si.edu/download/source/{{name}}.{{version}}.tar.gz

about:
    home: http://ds9.si.edu
    license: GPL,LGPL,BSD
    summary: FITS file viewer

