{% set name = "sphinx-automodapi" %}
{% set version = "0.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c989bfe37f555f635e8fbb650859df391556981f5a436507fb3241794fd26c6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - sphinx >=1.3
  run:
    - python
    - sphinx >=1.3

test:
  imports:
    - sphinx_automodapi
      #- sphinx_automodapi.tests
      #- sphinx_automodapi.tests.example_module

about:
  home: http://astropy.org
  license: BSD
  license_family: BSD
  license_file: 
  summary: Sphinx extension for auto-generating API documentation for entire modules
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
