{% set name = 'jwst_coronagraph_visibility' %}
{% set version = '0.4.2' %}
{% set number = '1' %}
{% set org = 'spacetelescope' %}

about:
    # Package homepage
    home: https://github.com/{{ org }}/{{ name }}
    # Package license
    license: BSD-3-Clause
    # A brief description
    summary: Visualize approximate pointing constraints for JWST coronagraphs.

package:
    # Define these values above
    name: {{ name }}
    version: {{ version }}

build:
    # Define this value above
    number: {{ number }}

source:
    fn: {{ version }}.tar.gz
    url: https://github.com/{{ org }}/{{ name }}/archive/{{ version }}.tar.gz

requirements:
    build:
    - setuptools
    - numpydoc
    - python {{ python }}
    - numpy {{ numpy }}
    - matplotlib>=2.2.4
    - tk
    - requests
    - pysiaf >=0.6.3
    run:
    - numpydoc
    - python
    - numpy
    - matplotlib
    - requests
    - tk
    - pysiaf >=0.6.3

test:
   imports:
   - jwst_coronagraph_visibility.skyvec2ins
