{% set name = 'jwst_coronagraph_visibility' %}
{% set version = '0.4.1' %}
{% set number = '1' %}

about:
    # Package homepage
    home: https://github.com/spacetelescope/jwst_coronagraph_visibility
    # Package license
    license: BSD-3-Clause
    # A brief description
    summary: Visualize approximate pointing constraints for JWST coronagraphs.

package:
    # Define these values above
    name: {{ name }}
    version: {{ version }}

build:
    # Define this value above
    number: {{ number }}

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

requirements:
    build:
    - setuptools
    - python {{ python }}
    - numpy {{ numpy }}
    - matplotlib
    - tk
    - requests
    - pysiaf>=0.6.3
    run:
    - python
    - numpy
    - matplotlib
    - requests
    - tk
    - pysiaf>=0.6.3

test:
   imports:
   - jwst_coronagraph_visibility.skyvec2ins
