{% set name = 'stsci.imagestats' %}
{% set version = '1.6.2' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Compute various useful statistical values for array objects

build:
    number: {{ number }}
    skip: True [py2k]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - setuptools
      - numpy {{ numpy }}
      - python {{ python }}

    run:
      - numpy
      - python

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git
    git_tag: {{ version }}

test:
    imports:
      - stsci.imagestats
