{% set name = 'webbpsf' %}
{% set version = '0.8.0' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://webbpsf.readthedocs.io
    license: BSD
    summary: |
        Creates simulated point spread functions for the James Webb Space Telescope

build:
    number: {{ number }}
    skip: true # [py27]
    preserve_egg_dir: 'True'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.2
    - numpy {{ numpy }}
    - scipy >=0.16.0
    - matplotlib >=1.5.0
    - poppy >=0.8.0
    - webbpsf-data ==0.8.0
    - setuptools
    - python {{ python }}
    - ipywidgets
    - jwxml
    - pysiaf >=0.1.8
    run:
    - astropy >=1.2
    - numpy {{numpy}}
    - scipy >=0.16.0
    - matplotlib >=1.5.0
    - poppy >=0.8.0
    - webbpsf-data ==0.8.0
    - setuptools
    - python
    - ipywidgets
    - jwxml
    - pysiaf >=0.1.8

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/webbpsf

test:
    commands:
    - WEBBPSF_PATH=$PREFIX/share/webbpsf-data python -c 'import webbpsf'
