{% set name = 'webbpsf' %}
{% set version = '1.0.0' %}
{% set tag = 'v' + version %}
{% set number = '1' %}

about:
    home: https://webbpsf.readthedocs.io
    license: BSD
    summary: |
        Creates simulated point spread functions for the James Webb Space Telescope

build:
    number: {{ number }}
    skip: true # [py27]
    preserve_egg_dir: 'True'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=4.0.0
    - numpy >=1.18.0
    - numpydoc
    - scipy >=1.5.0
    - matplotlib >=3.2.0
    - poppy ==1.0.1
    - photutils
    - webbpsf-data ==1.0.0
    - setuptools
    - setuptools_scm
    - python {{ python }}
    - ipywidgets
    - pysiaf >=0.11.0
    - synphot >=1.0.0
    run:
    - astropy >=4.0.0
    - numpy >=1.18.0
    - numpydoc
    - scipy >=1.5.0
    - matplotlib >=3.2.0
    - poppy ==1.0.1
    - photutils
    - webbpsf-data ==1.0.0
    - setuptools
    - setuptools_scm
    - python
    - ipywidgets
    - pysiaf >=0.11.0
    - synphot >=1.0.0

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/webbpsf

test:
    commands:
    - WEBBPSF_PATH=$PREFIX/share/webbpsf-data python -c 'import webbpsf'
