{% set name = 'webbpsf' %}
{% set version = '0.9.0' %}
{% set tag = 'v' + version %}
{% set number = '1' %}

about:
    home: https://webbpsf.readthedocs.io
    license: BSD
    summary: |
        Creates simulated point spread functions for the James Webb Space Telescope

build:
    number: {{ number }}
    skip: true # [py27]
    preserve_egg_dir: 'True'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=3.0.0
    - numpy {{ numpy }}
    - numpydoc
    - scipy >=1.0.0
    - matplotlib >=2.0.0
    - poppy >=0.9.0
    - photutils
    - webbpsf-data ==0.9.0
    - setuptools
    - python {{ python }}
    - ipywidgets
    - jwxml
    - pysiaf >=0.6.0
    run:
    - astropy >=3.0.0
    - numpy
    - numpydoc
    - scipy >=1.0.0
    - matplotlib >=2.0.0
    - poppy >=0.9.0
    - photutils
    - webbpsf-data ==0.9.0
    - setuptools
    - python
    - ipywidgets
    - jwxml
    - pysiaf >=0.6.0

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/webbpsf

test:
    commands:
    - WEBBPSF_PATH=$PREFIX/share/webbpsf-data python -c 'import webbpsf'
