{% set name = 'webbpsf' %}
{% set version = '0.5.1' %}
{% set tag = 'v' + version %}
{% set number = '1' %}

about:
    home: https://github.com/mperrin/{{ name }}
    license: BSD
    summary: |
        Creates simulated point spread functions for the James Webb Space Telescope

build:
    number: {{ number }}
    preserve_egg_dir: 'True'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - numpy
    - scipy
    - matplotlib
    - poppy >=0.5.1
    - six [py27]
    - webbpsf-data ==0.5.0
    - setuptools
    - python x.x
    - ipywidgets
    - jwxml
    run:
    - astropy >=1.1
    - numpy
    - scipy
    - matplotlib
    - poppy >=0.5.1
    - six [py27]
    - webbpsf-data ==0.5.0
    - setuptools
    - python x.x
    - ipywidgets
    - jwxml

source:
    git_tag: {{ tag }}
    git_url: https://github.com/mperrin/webbpsf

test:
    commands:
    - WEBBPSF_PATH=$PREFIX/share/webbpsf-data python -c 'import webbpsf'
