{% set name = 'specutils' %}
{% set version = GIT_DESCRIBE_TAG ~ ".dev" ~ GIT_DESCRIBE_NUMBER ~ "+" ~ GIT_DESCRIBE_HASH %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '0' %}

about:
    home: https://github.com/astropy/specutils
    license: BSD
    summary: One-dimensional spectral operations

package:
    name: {{ name }}
    version: {{ version }}

build:
    number: {{ number }}

source:
    # This hash is set to the most recent commit on the legacy-specutils branch
    git_rev: 5651be27d26715f9ca3aa5f8380cdc0d963ad2f6
    git_url: https://github.com/astropy/{{ name }}.git

requirements:
    build:
    - astropy
    - cython
    - scipy
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy
    - scipy
    - numpy
    - python

test:
    imports:
    - specutils
    - specutils.io
    - specutils.models
    - specutils.utils
    - specutils.wcs

