{% set name = 'specutils' %}
{% set version = '0.5.2' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/astropy/specutils
    license: BSD
    summary: One-dimensional spectral operations

package:
    name: {{ name }}
    version: {{ version }}

build:
    number: {{ number }}
    skip: true # [py27]

source:
    git_tag: {{ tag }}
    git_url: https://github.com/astropy/{{ name }}.git

requirements:
    build:
    - astropy
    - scipy
    - gwcs
    - six
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy
    - scipy
    - gwcs
    - six
    - numpy
    - python

test:
    imports:
    - specutils
    - specutils.analysis
    - specutils.fitting
    - specutils.io
    - specutils.manipulation
    - specutils.spectra
    - specutils.utils
    - specutils.wcs
