{% set name = 'stwcs' %}
{% set version = '1.5.3' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        WCS based distortion models and coordinate transformation

build:
    number: {{ number }}
    skip: True [py27]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy
    - lxml
    - pytest
    - requests
    - stsci.tools >= 3.6
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy
    - lxml
    - requests
    - stsci.tools >=3.6
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stwcs
