{% set name = 'stginga' %}
{% set version = '0.1.3' %}
{% set tag = version %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Ginga products specific to STScI data analysis
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - ginga >= 2.6.1
    - astropy >=1.2
    - numpy x.x
    - scipy
    - setuptools
    - python x.x
    run:
    - ginga >= 2.6.1
    - astropy >=1.2
    - numpy x.x
    - scipy
    - python x.x
source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
test:
    imports:
    - stginga
