{% set name = 'stginga' %}
{% set version = '1.3.0' %}
{% set tag = version %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Ginga products specific to STScI data analysis

build:
    number: {{ number }}
    skip: true  # [py2k]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - ginga >=2.7
    - astropy >=3
    - numpy {{ numpy }}
    - scipy >=0.18
    - setuptools_scm
    - setuptools
    - python {{ python }}
    run:
    - ginga >=2.7
    - astropy >=3
    - numpy
    - scipy >=0.18
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stginga
