about:
    home: https://github.com/ericmandel/pyds9
    license: GPL
    summary: |
        (Supervised master build)
        Python connection to SAOimage DS9 via XPA
build:
    number: '0'
    string: {{ GIT_BUILD_STR }}
package:
    name: pyds9
    version: 1.9.0.dev
requirements:
    build:
    - astropy
    - cython
    - ds9
    - six
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy
    - ds9
    - six
    - numpy x.x
    - python x.x
source:
    git_rev: 3761d7ac151f8c8729d0fb6cdba017cadf278283
    git_url: https://github.com/ericmandel/pyds9
test:
    imports:
    - pyds9
