{% set name = 'calcos' %}
{% set version = '3.3.8' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    summary: Calibration for HST/COS

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - scipy
    - stsci.tools
    - setuptools
    - setuptools_scm
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=1.1
    - scipy
    - stsci.tools
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - calcos -r
    imports:
    - calcos
