{% set name = 'calcos' %}
{% set version = '3.1.8' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    summary: Calibration for HST/COS
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - d2to1
    - astropy >=1.1
    - scipy
    - stsci.distutils
    - stsci.tools
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - astropy >=1.1
    - scipy
    - stsci.tools
    - numpy x.x
    - python x.x
source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
test:
    commands:
    - calcos -r
    imports:
    - calcos
