
{% set name = 'cube-tools' %}
{% set version = '0.0.1' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Data analysis package for cubes.
build:
    number: {{ number }}
package:
    name: cube-tools
    version: {{ version }}
requirements:
    build:
    - glueviz
    - specview
    - pyqtgraph
    - setuptools
    - numpy x.x
    - python x.x
    run:
    - glueviz
    - specview
    - pyqtgraph
    - numpy x.x
    - python x.x
source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
test:
    imports:
    - cube_tools
