{% set name = "asteval" %}
{% set version = "0.9.13" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "8faf9f92b2b0d2ed376dc149d6bab2e01f614f6994722be9c16f982cbdd07c99" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools
    - numpy {{ numpy }}
    - six
  run:
    - python
    - numpy
    - six

test:
  imports:
    - asteval

about:
  home: http://github.com/newville/asteval
  license: BSD License
  license_family: BSD
  license_file: ''
  summary: Safe, minimalistic evaluator of python expression using ast module
  description: 'ASTEVAL provides a numpy-aware, safe(ish) ''eval'' function


    Emphasis is on mathematical expressions, and so numpy ufuncs

    are used if available.  Symbols are held in the Interpreter

    symbol table ''symtable'':  a simple dictionary supporting a

    simple, flat namespace.


    Expressions can be compiled into ast node for later evaluation,

    using the values in the symbol table current at evaluation time.'
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
