{% set name = 'astroquery' %}
{% set version = '0.3.7' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set tag = 'v' + version %}
{% set number = '1' %}

about:
    home: https://github.com/astropy/{{ name }}
    license: BSD
    summary: Astroquery is a set of tools for querying astronomical web forms and databases.

package:
    name: {{ name }}
    version: {{ version }}

source:
    git_url: https://github.com/astropy/{{ name }}
    git_tag: {{ tag }}

build:
    number: {{ number }}

requirements:
    build:
    - astropy
    - requests
    - keyring
    - beautifulsoup4
    - html5lib
    - secretstorage [linux]
    - setuptools
    - python {{ python }}

    run:
    - astropy
    - requests
    - keyring
    - beautifulsoup4
    - html5lib
    - secretstorage [linux]
    - python

test:
    imports:
    - astroquery.simbad
