{% set name = 'astroquery' %}
{% set version = '0.3.5' %}
{% set number = '0' %}

about:
    home: https://github.com/astropy/{{ name }}
    license: BSD
    summary: Astroquery is a set of tools for querying astronomical web forms and databases.

package:
    name: {{ name }}
    version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 1be83c630fcb462a711eb9c2eda0fbea

build:
    number: {{ number }}

requirements:
    build:
    - astropy
    - requests
    - keyring
    - beautifulsoup4
    - html5lib
    - setuptools
    - python x.x
    run:
    - astropy
    - requests
    - keyring
    - beautifulsoup4
    - html5lib
    - python x.x

test:
    imports:
    - astroquery.simbad
