{% set name = 'stsci_rtd_theme' %}
{% set version = '0.0.1' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        ReadTheDocs.org theme for STScI

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - sphinx
      - setuptools
      - python {{ python }}

    run:
      - sphinx
      - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
      - stsci_rtd_theme
