{% set name = 'stistools' %}
{% set version = '1.2' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Tools for STIS (Space Telescope Imaging Spectrograph)

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - astropy >=1.1
    - scipy
    - stsci.distutils
    - stsci.tools
    - stsci_rtd_theme
    - sphinx_rtd_theme
    - numpydoc
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=1.1
    - scipy
    - stsci.tools
    - numpy
    - python

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stistools
